### ISSUE TITLE
Cannot start D-Rats 0.3.10beta4

### ISSUE THREAD

**Issue by miodzicho** [maurizioandreotti/D-Rats#104]
It is failing with 👍 
`Traceback (most recent call last):
  File "/usr/local/bin/d-rats.py", line 34, in <module>
    from d_rats import utils, spell
  File "/usr/local/lib/python2.7/dist-packages/d_rats/utils.py", line 29, in <module>
    from . import dplatform
  File "/usr/local/lib/python2.7/dist-packages/d_rats/dplatform.py", line 167
    'if yes connected=true return url to be connect
                                                  ^
SyntaxError: EOL while scanning string literal`

**Comment by maurizioandreotti** [comment]
happens when one has too many hours on VBA and forgets to use #
