### ISSUE TITLE
file transfer - JPG transfer error

### ISSUE THREAD

**Issue by maurizioandreotti** [maurizioandreotti/D-Rats#50]
On attempting to do a File Transfer of a .JPG file, the following error was received:

---- GUI Exception ----
Traceback (most recent call last):
 
  File "d_rats\ui\main_files.pyo", line 236, in _upload
 
  File "d_rats\image.pyo", line 117, in send_image
 
NameError: global name 'main_common' is not defined
 
---- End ----
 
Msgrouting: Running routing loop

Transfers of .PDF, .TXT, and other documents seem to go through fine, but in the old stable version, the program would call up a routine giving you the opportunity to resize the photo before sending it.  The new version gives an error and will not pass the file to the other station.  I pulled up the old version and sent it over, but this is something to keep in mind until fixed.

**Comment by maurizioandreotti** [comment]
from email by Glen: 
Further testing shows that another station can connect, request, and receive a .JPG file with no problems.  The problem only arises when your station attempts to Upload a .JPG file to another station.  Until the problem is addressed, the workaround would be to tell the other station, either through CHAT or email to request the photo that you want them to see.

**Comment by maurizioandreotti** [comment]
solved adding import of main_common from .ui
