### ISSUE TITLE
0.3.8 - winlink error on windows

### ISSUE THREAD

**Issue by maurizioandreotti** [maurizioandreotti/D-Rats#51]
running the code on windows (both compiled and intepreted), sending a winlink email (and a plain d-rats email also) i get this error:

Traceback (most recent call last):
  File "d_rats\msgrouting.pyo", line 510, in _run_one
  File "d_rats\msgrouting.pyo", line 484, in _route_message
  File "d_rats\msgrouting.pyo", line 461, in _route_via_wl2k
NameError: global name 'mainapp' is not defined
------
which blocks the email send

the same error do NOT show executing on linux (which sends the email)

i suspect it is correlated to the imports i had to comment as the new code on linux was complaining. need to undestand if the import needs to be different  in case the code is executed on windows or linux (i hope it's not...)

**Comment by maurizioandreotti** [comment]
fixed forcing "mainapp" import in the scope where is needed (at beginning of the module it doesnt work anymore)
