### ISSUE TITLE
emailgw issue

### ISSUE THREAD

**Issue by maurizioandreotti** [maurizioandreotti/D-Rats#65]
gmail address set up on drats.
 recently it stopped working. Here is the log:

-- Exception: --
Traceback (most recent call last):
  File "/home/pi/drats/d_rats/msgrouting.py", line 515, in _run_one
    routed = self._route_message(msg, slist, routes)
  File "/home/pi/drats/d_rats/msgrouting.py", line 484, in _route_message
    route = self._route_msg(src, dst, path, slist, routes)
  File "/home/pi/drats/d_rats/msgrouting.py", line 334, in _route_msg
    emailgw.validate_incoming(self.__config, src, dst):
NameError: global name 'emailgw' is not defined
------
Msgrouting: unlocking message /home/pi/.d-rats-ev/messages/Outbox/form_05142020_183659.xml

**Comment by maurizioandreotti** [comment]
closed in 0.3.9 beta2
